"""add_chat_histories_table

Revision ID: 04a73a182130
Revises: f28c4eefa82a
Create Date: 2026-08-04 15:52:03.665623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a73a182130'
down_revision: Union[str, Sequence[str], None] = 'f28c4eefa82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_histories_session_id'), 'chat_histories', ['session_id'], unique=True)
    # ### end Alembic commands ###

    # --- Data Migration: Move existing chat sessions to target user ---
    import uuid
    import datetime

    conn = op.get_bind()

    # Find the target user
    target_email = "praveen.kumarbb392@gamil.com"
    user_row = conn.execute(
        sa.text("SELECT id FROM users WHERE email = :email"),
        {"email": target_email}
    ).fetchone()

    if user_row:
        user_id = user_row[0]

        # Query distinct thread_ids from LangGraph's checkpoints table
        try:
            thread_rows = conn.execute(
                sa.text("SELECT DISTINCT thread_id FROM checkpoints")
            ).fetchall()
        except Exception:
            # checkpoints table may not exist yet
            thread_rows = []

        now = datetime.datetime.now(datetime.timezone.utc)
        for row in thread_rows:
            thread_id = row[0]
            conn.execute(
                sa.text(
                    "INSERT INTO chat_histories (id, user_id, session_id, title, created_at, updated_at) "
                    "VALUES (:id, :user_id, :session_id, :title, :created_at, :updated_at) "
                    "ON CONFLICT (session_id) DO NOTHING"
                ),
                {
                    "id": str(uuid.uuid4()),
                    "user_id": str(user_id),
                    "session_id": thread_id,
                    "title": f"Session {thread_id}",
                    "created_at": now,
                    "updated_at": now,
                },
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_histories_session_id'), table_name='chat_histories')
    op.drop_table('chat_histories')
    # ### end Alembic commands ###
